"""
build_capacity_curve.py  —  通用信道遍历容量曲线预计算脚本
========================================================
功能：扫描 SNR 范围 [-20, 5] dB（步进 0.5 dB），逐点调用 MATLAB
      calc_channel_capacity() 计算容量，将结果序列化为 JSON 落盘。

支持信道模型（通过 --channel 参数指定）：
  AWGN       — 直接套用香农公式，极速完成
  TDL-C      — 非视距多径衰落，1000 次蒙特卡洛
  TDL-D      — 视距多径衰落，1000 次蒙特卡洛
  （其他 TDL-* 均支持）

输出文件名根据参数动态生成，例如：
  capacity_curve_AWGN.json
  capacity_curve_TDL-C_100ns.json
  capacity_curve_TDL-D_30ns.json

运行方式（必须使用项目虚拟环境）：
    cd /Users/wtx/Developer/Semantic_Debug
    venv.nosync/bin/python av1_ldpc_ofdm_matlab/build_capacity_curve.py
    venv.nosync/bin/python av1_ldpc_ofdm_matlab/build_capacity_curve.py --channel TDL-C --ds 100e-9
    venv.nosync/bin/python av1_ldpc_ofdm_matlab/build_capacity_curve.py --channel AWGN
"""

import argparse
import json
import os
import sys

import numpy as np

# ── 命令行参数解析 ─────────────────────────────────────────────
parser = argparse.ArgumentParser(description="预计算信道遍历容量曲线")
parser.add_argument("--channel", type=str, default="TDL-C",
                    help="信道模型，如 AWGN、TDL-C、TDL-D（默认：TDL-C）")
parser.add_argument("--ds", type=float, default=100e-9,
                    help="时延扩展（秒），AWGN 时忽略（默认：100e-9）")
args = parser.parse_args()

CHANNEL_MODEL = args.channel
DELAY_SPREAD  = args.ds

# ── 路径配置 ──────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# 动态生成输出文件名
if CHANNEL_MODEL == "AWGN":
    OUTPUT_JSON = os.path.join(SCRIPT_DIR, "capacity_curve_AWGN.json")
else:
    # 将秒转为 ns 便于阅读，如 100e-9 → 100ns
    ds_ns = int(round(DELAY_SPREAD * 1e9))
    OUTPUT_JSON = os.path.join(SCRIPT_DIR, f"capacity_curve_{CHANNEL_MODEL}_{ds_ns}ns.json")

# ── SNR 扫频参数 ──────────────────────────────────────────────
SNR_START = -20.0   # dB
SNR_STOP  =   5.0   # dB
SNR_STEP  =   0.5   # dB

snr_array = np.arange(SNR_START, SNR_STOP + SNR_STEP * 0.5, SNR_STEP)
total     = len(snr_array)

print("=" * 60)
print(f"信道遍历容量曲线预计算")
print(f"  信道模型  : {CHANNEL_MODEL}")
if CHANNEL_MODEL != "AWGN":
    print(f"  时延扩展  : {DELAY_SPREAD * 1e9:.0f} ns")
print(f"  SNR 范围  : [{SNR_START}, {SNR_STOP}] dB")
print(f"  步进      : {SNR_STEP} dB")
print(f"  总计算点数: {total}")
print(f"  输出文件  : {OUTPUT_JSON}")
print("=" * 60)

# ── 启动 MATLAB Engine ────────────────────────────────────────
print("\n正在启动 MATLAB Engine（共享引擎 JSCC_Engine）...")
import matlab.engine  # noqa: E402  — 放在 print 之后，便于提前看到提示

try:
    eng = matlab.engine.connect_matlab('JSCC_Engine')
    print("已连接到后台共享引擎 JSCC_Engine。")
except Exception:
    print("未找到共享引擎，正在启动新的 MATLAB 实例（首次启动约需 30 秒）...")
    eng = matlab.engine.start_matlab()
    print("MATLAB Engine 启动成功。")

# 将 MATLAB worker 目录加入路径，确保 calc_channel_capacity 可被调用
eng.addpath(SCRIPT_DIR, nargout=0)
print(f"已将 {SCRIPT_DIR} 加入 MATLAB 路径。\n")

# ── 逐点计算容量 ──────────────────────────────────────────────
capacity_list: list[float] = []

for idx, snr_db in enumerate(snr_array):
    cap = float(eng.calc_channel_capacity(
        float(snr_db),
        CHANNEL_MODEL,
        float(DELAY_SPREAD),
        nargout=1
    ))
    capacity_list.append(cap)

    # 进度日志：每点都打印，方便监控耗时
    bar_filled = int((idx + 1) / total * 30)
    bar        = "█" * bar_filled + "░" * (30 - bar_filled)
    print(f"  [{idx+1:3d}/{total}] [{bar}]  SNR={snr_db:+6.1f} dB  C={cap:.6f} bits/s/Hz")
    sys.stdout.flush()

print("\n所有 SNR 点计算完毕。")

# ── 序列化落盘 ────────────────────────────────────────────────
if CHANNEL_MODEL == "AWGN":
    ds_ns_val = 0
    desc_str = (
        f"AWGN ergodic capacity curve (Shannon formula). "
        f"X=snr_db, Y=capacity (bits/s/Hz). "
        f"Generated by build_capacity_curve.py."
    )
else:
    ds_ns_val = int(round(DELAY_SPREAD * 1e9))
    desc_str = (
        f"{CHANNEL_MODEL} ergodic capacity curve (DelaySpread={ds_ns_val}ns). "
        f"X=snr_db, Y=capacity (bits/s/Hz). "
        f"Generated by build_capacity_curve.py via 1000-trial Monte Carlo."
    )

payload = {
    "snr_db":   snr_array.tolist(),
    "capacity": capacity_list,
    "meta": {
        "channel_model": CHANNEL_MODEL,
        "delay_spread_ns": ds_ns_val,
        "snr_start": SNR_START,
        "snr_stop":  SNR_STOP,
        "snr_step":  SNR_STEP,
        "total_points": total,
        "description": desc_str,
    },
}

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2)

print(f"[落盘完成] 容量曲线已保存至: {OUTPUT_JSON}")
print(f"  共 {total} 个数据点，SNR 范围 [{SNR_START}, {SNR_STOP}] dB。")

# ── 关闭 MATLAB Engine ────────────────────────────────────────
eng.quit()
print("\nMATLAB Engine 已关闭。")
print("=" * 60)
print("预计算完成！现在可以运行 run_sim.py 进行主仿真。")
