"""
build_capacity_curve.py  —  TDL-C 遍历容量曲线预计算脚本
========================================================
功能：扫描 SNR 范围 [-15, 30] dB（步进 0.5 dB），逐点调用 MATLAB
      calc_tdlc_capacity() 蒙特卡洛仿真，将结果序列化为 JSON 落盘。

输出文件：tdlc_capacity_curve.json（与本脚本同目录）
用途：供 run_sim.py 在启动时预加载，实现毫秒级 SNR 极限查表，
      彻底解耦主仿真循环与耗时 MATLAB 蒙特卡洛调用。

运行方式（必须使用项目虚拟环境）：
    cd /Users/wtx/Developer/Semantic_Debug
    venv.nosync/bin/python av1_ldpc_ofdm_matlab/build_capacity_curve.py
"""

import json
import os
import sys

import numpy as np

# ── 路径配置 ──────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_JSON = os.path.join(SCRIPT_DIR, "tdlc_capacity_curve.json")

# ── SNR 扫频参数 ──────────────────────────────────────────────
SNR_START = -20.0   # dB
SNR_STOP  =  5.0   # dB
SNR_STEP  =   0.5   # dB

snr_array = np.arange(SNR_START, SNR_STOP + SNR_STEP * 0.5, SNR_STEP)
total     = len(snr_array)

print("=" * 60)
print("TDL-C 遍历容量曲线预计算")
print(f"  SNR 范围  : [{SNR_START}, {SNR_STOP}] dB")
print(f"  步进      : {SNR_STEP} dB")
print(f"  总计算点数: {total}")
print(f"  输出文件  : {OUTPUT_JSON}")
print("=" * 60)

# ── 启动 MATLAB Engine ────────────────────────────────────────
print("\n正在启动 MATLAB Engine（共享引擎 JSCC_Engine）...")
import matlab.engine  # noqa: E402  — 放在 print 之后，便于提前看到提示

try:
    eng = matlab.engine.connect_matlab('JSCC_Engine')
    print("已连接到后台共享引擎 JSCC_Engine。")
except Exception:
    print("未找到共享引擎，正在启动新的 MATLAB 实例（首次启动约需 30 秒）...")
    eng = matlab.engine.start_matlab()
    print("MATLAB Engine 启动成功。")

# 将 MATLAB worker 目录加入路径，确保 calc_tdlc_capacity 可被调用
eng.addpath(SCRIPT_DIR, nargout=0)
print(f"已将 {SCRIPT_DIR} 加入 MATLAB 路径。\n")

# ── 逐点计算容量 ──────────────────────────────────────────────
capacity_list: list[float] = []

for idx, snr_db in enumerate(snr_array):
    cap = float(eng.calc_tdlc_capacity(float(snr_db), nargout=1))
    capacity_list.append(cap)

    # 进度日志：每点都打印，方便监控耗时
    bar_filled = int((idx + 1) / total * 30)
    bar        = "█" * bar_filled + "░" * (30 - bar_filled)
    print(f"  [{idx+1:3d}/{total}] [{bar}]  SNR={snr_db:+6.1f} dB  C={cap:.6f} bits/s/Hz")
    sys.stdout.flush()

print("\n所有 SNR 点计算完毕。")

# ── 序列化落盘 ────────────────────────────────────────────────
payload = {
    "snr_db":   snr_array.tolist(),
    "capacity": capacity_list,
    "meta": {
        "snr_start": SNR_START,
        "snr_stop":  SNR_STOP,
        "snr_step":  SNR_STEP,
        "total_points": total,
        "description": (
            "TDL-C ergodic capacity curve. "
            "X=snr_db, Y=capacity (bits/s/Hz). "
            "Generated by build_capacity_curve.py via 1000-trial Monte Carlo."
        ),
    },
}

with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
    json.dump(payload, f, indent=2)

print(f"[落盘完成] 容量曲线已保存至: {OUTPUT_JSON}")
print(f"  共 {total} 个数据点，SNR 范围 [{SNR_START}, {SNR_STOP}] dB。")

# ── 关闭 MATLAB Engine ────────────────────────────────────────
eng.quit()
print("\nMATLAB Engine 已关闭。")
print("=" * 60)
print("预计算完成！现在可以运行 run_sim.py 进行主仿真。")
print("=" * 60)
